export const FEEDBACK_STRINGS: Record<string, string> = {
  'feedback.trigger.label': 'Send feedback',
  'feedback.dialog.title': 'Send feedback',
  'feedback.dialog.description': 'Tell us what you experienced. Attach screenshots or files if helpful.',
  'feedback.field.body.label': 'Details',
  'feedback.field.body.hint': 'Tip: paste a screenshot directly into the box below.',
  'feedback.dialog.submit': 'Submit',
  'feedback.dialog.cancel': 'Cancel',
  'feedback.dialog.submitting': 'Submitting...',
  'feedback.category.bug': 'Bug',
  'feedback.category.feature': 'Feature request',
  'feedback.category.general': 'General feedback',
  'feedback.category.praise': 'Praise',
  'feedback.field.subject.placeholder': 'What went wrong?',
  'feedback.field.body.placeholder': 'Describe the issue in detail...',
  'feedback.field.problem.label': 'What happened?',
  'feedback.field.expected.label': 'What did you expect?',
  'feedback.field.reproducibility.label': 'How often does this happen?',
  'feedback.field.reproducibility.always': 'Every time',
  'feedback.field.reproducibility.sometimes': 'Sometimes',
  'feedback.field.reproducibility.once': 'Just once',
  'feedback.field.intent.label': 'What are you trying to accomplish?',
  'feedback.success.title': 'Thanks for your feedback!',
  'feedback.success.refId': 'Reference: {{ref_id}}',
  'feedback.success.copy': 'Copy reference',
  'feedback.success.copied': 'Copied!',
  'feedback.success.close': 'Close',
  'feedback.attachment.add': 'Attach a file',
  'feedback.attachment.screenshot': 'Take screenshot',
  'feedback.attachment.tooLarge': 'File too large (max {{max}})',
  'feedback.attachment.tooMany': 'Maximum {{max}} attachments',
  'feedback.privacy.notice': 'This feedback includes your current page context to help us debug.',
  'feedback.error.submit': 'Failed to submit. Please try again.',
  'feedback.error.rateLimit': 'Too many submissions. Please wait a moment.',
  'feedback.admin.title': 'Feedback inbox',
  'feedback.admin.empty': 'No feedback yet',
  'feedback.admin.copyPrompt': 'Copy AI prompt',
  'feedback.admin.promptCopied': 'Copied to clipboard',
  'feedback.admin.export': 'Export',

  // R5 — thread
  'thread.loading':              'Loading…',
  'thread.empty':                'No replies yet.',
  'thread.no_subject':           '(no subject)',
  'thread.author.admin':         'Admin',
  'thread.author.you':           'You',
  'thread.cannot_reply':         'Replies open after an admin responds.',
  'thread.compose.placeholder':  'Reply…',
  'thread.compose.send':         'Send reply',
  'thread.compose.sending':      'Sending…',
  'thread.error.unauthorized':   'Please sign in to view this thread.',
  'thread.error.forbidden':      'You do not have access to this thread.',
  'thread.error.not_found':      'Thread not found.',

  // R2 — public board
  'board.title':                 'Feature requests',
  'board.loading':               'Loading…',
  'board.empty':                 'No public feature requests yet.',
  'board.no_subject':            '(no subject)',
  'board.vote.toggle':           'Toggle vote',
  'board.sort.top':              'Top',
  'board.sort.new':              'New',
  'board.prev':                  'Previous',
  'board.next':                  'Next',
  'board.page':                  'Page {page} of {total}',
  'board.error.unauthorized':    'Please sign in to view feature requests.',
};
